
name: "Hello action"
description: "Sharing actions with devcontainers"
runs:
  using: "docker"
  image: "../docker/Dockerfile"
inputs:
  preCommands:
    description: "Commands to execute before publishing the project"
    required: false
  postCommands:
    description: "Commands to execute after publishing the project"
    required: false
